/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app */

#ifndef _Included_app
#define _Included_app
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
