/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DotProduct */
/*
 * Class:     DotProduct
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */

JNIEXPORT jdouble JNICALL Java_DotProduct_multi01
  (JNIEnv * e1, jobject o1, jdoubleArray a1, jdoubleArray b1)
  {
  	jsize lena = (*e1)->GetArrayLength(e1, a1);

  	jdouble *_a = (*e1)->GetDoubleArrayElements(e1, a1, 0);
  	jdouble *_b = (*e1)->GetDoubleArrayElements(e1, b1, 0);

  	double result = 0;
  	for (int i = 0; i < lena; i++) {
  		result += _a[i] * _b[i];
  	}

  	return result;
  	double v = 1.0;
  	//return 1.0;
  };

/*
 * Class:     DotProduct
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jdouble JNICALL Java_DotProduct_multi02
  (JNIEnv * e, jobject o, jdoubleArray a)
  {
  	jsize lena = (*e)->GetArrayLength(e, a);

  	jdouble *_a = (*e)->GetDoubleArrayElements(e, a, 0);

  	jclass cls = (*e)->FindClass(e, "DotProduct");  
    jfieldID fid = (*e)->GetFieldID(e, cls, "b", "[D");  

    jobject temp = (*e)->GetObjectField(e, o, fid);
    jdoubleArray* temp2 = (jdoubleArray*)(&temp);
    jdouble* _b = (*e)->GetDoubleArrayElements(e, *temp2, 0);

    double result = 0;
    for (int i = 0; i < lena; i++) {
    	result += _a[i] * _b[i];
    }

    return result;
  };

JNIEXPORT void JNICALL Java_DotProduct_hello(JNIEnv * e, jobject o)
{
	printf("hello");
	return;
}


 /* Class:     DotProduct
 * Method:    multi03
 * Signature: ()V */
 
JNIEXPORT void JNICALL Java_DotProduct_multi03
  (JNIEnv * e, jobject o)
  {
    jdouble a = 0;
    jdouble b = 0;
    scanf("%lf%lf", &a, &b);

    jdouble w = a * b;
    printf("%lf", w);
  }
